#!/usr/bin/env python3
"""
DS2API Config Generator for Render.com
Generates config.json from environment variables.
"""

import json
import os

def generate_config():
    config = {
        "_comment": "Auto-generated by Render entrypoint",
        "_doc": "https://github.com/CJackHwang/ds2api"
    }

    # --- API Keys ---
    api_keys = []
    api_key_env = os.environ.get("API_KEY", "")
    if api_key_env:
        keys = [k.strip() for k in api_key_env.split(",") if k.strip()]
        for i, key in enumerate(keys):
            api_keys.append({
                "key": key,
                "name": f"API Key {i+1}",
                "remark": "Auto-generated from env"
            })

    if api_keys:
        config["api_keys"] = api_keys
        config["keys"] = [k["key"] for k in api_keys]

    # --- DeepSeek Accounts ---
    accounts = []

    # Account 1 (Email + Password)
    ds_email = os.environ.get("DS_EMAIL", "")
    ds_password = os.environ.get("DS_PASSWORD", "")
    if ds_email and ds_password:
        accounts.append({
            "name": "Primary Account",
            "email": ds_email,
            "password": ds_password
        })

    # Account 2 (optional)
    ds_email_2 = os.environ.get("DS_EMAIL_2", "")
    ds_password_2 = os.environ.get("DS_PASSWORD_2", "")
    if ds_email_2 and ds_password_2:
        accounts.append({
            "name": "Secondary Account",
            "email": ds_email_2,
            "password": ds_password_2
        })

    # Account with Token
    ds_token = os.environ.get("DS_TOKEN", "")
    if ds_token:
        accounts.append({
            "name": "Token Account",
            "token": ds_token
        })

    if accounts:
        config["accounts"] = accounts

    # --- Model Aliases ---
    model_aliases_env = os.environ.get("MODEL_ALIASES", "")
    if model_aliases_env:
        try:
            config["model_aliases"] = json.loads(model_aliases_env)
        except json.JSONDecodeError:
            print("[config] Warning: MODEL_ALIASES is not valid JSON, using defaults")
            config["model_aliases"] = {
                "gpt-4o": "deepseek-v4-flash",
                "gpt-5.5": "deepseek-v4-flash",
                "gpt-5.3-codex": "deepseek-v4-pro",
                "o3": "deepseek-v4-pro"
            }
    else:
        config["model_aliases"] = {
            "gpt-4o": "deepseek-v4-flash",
            "gpt-5.5": "deepseek-v4-flash",
            "gpt-5.3-codex": "deepseek-v4-pro",
            "o3": "deepseek-v4-pro"
        }

    # --- Admin Config ---
    config["admin"] = {
        "jwt_expire_hours": 24
    }

    # --- Runtime Config ---
    config["runtime"] = {
        "account_max_inflight": 2,
        "account_max_queue": 0,
        "global_max_inflight": 0,
        "token_refresh_interval_hours": 6
    }

    # --- Responses ---
    config["responses"] = {
        "store_ttl_seconds": 900
    }

    # --- Embeddings ---
    config["embeddings"] = {
        "provider": "deterministic"
    }

    # --- Thinking Injection ---
    config["thinking_injection"] = {
        "enabled": True,
        "prompt": ""
    }

    # --- Current Input File ---
    config["current_input_file"] = {
        "enabled": True,
        "min_chars": 0
    }

    # --- Auto Delete ---
    config["auto_delete"] = {
        "mode": "none"
    }

    # Write config
    os.makedirs("/data", exist_ok=True)
    with open("/data/config.json", "w") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    # Print summary
    print(f"[config] Accounts configured: {len(accounts)}")
    print(f"[config] API Keys configured: {len(api_keys)}")
    if accounts:
        for acc in accounts:
            if "email" in acc:
                print(f"[config]   - {acc['name']}: {acc['email']}")
            elif "token" in acc:
                print(f"[config]   - {acc['name']}: <token>")

if __name__ == "__main__":
    generate_config()
